msit116apexLayout/Controllers/PowerConfirmController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using msit116apexLayout.Models;
using Microsoft.AspNet.Identity;

namespace msit116apexLayout.Controllers
{
    [Authorize]
    public class PowerConfirmController : Controller
    {
        MSIT116APEXEntities db = new MSIT116APEXEntities();
        Repository<uRolePowerConfirm> dbuRolePowerConfirm = new Repository<uRolePowerConfirm>();
        // GET: PowerConfirm
        public ActionResult Index()
        {            
            return View();
        }

        public PartialViewResult ViewRoleConfirm(int roleID)
        {
            List<uPowerWithBoolPage> upwbpList = new List<uPowerWithBoolPage>();
            IEnumerable<uRoles> uRoles = db.uRoles.ToList();
            IEnumerable<uPages> uPages = db.uPages.ToList();
            IEnumerable<uPowers> uPowers = db.uPowers.ToList();
            IEnumerable<uRolePowers> uRolePowers = db.uRolePowers.ToList();
            IEnumerable<uRolePowerConfirm> uRolePowerConfirm = db.uRolePowerConfirm.ToList();
            IEnumerable<uRolePowerConfirmRole> uRolePowerConfirmRole = db.uRolePowerConfirmRole.ToList();
            IEnumerable<Department> department = db.Department.ToList();
            foreach (var upage in uPages)
            {
                List<uPowerWithBool> upwbList = new List<uPowerWithBool>();
                foreach (var upower in uPowers.Where(n => n.pageID == upage.pageID))
                {
                    bool haspower = (from c in uRolePowers
                                     where c.uRoleID == roleID && c.powerID == upower.powerID
                                     select c.powerID).Count() > 0;

                    IEnumerable<int> croleList = from urp in uRolePowers
                                                 join urpc in uRolePowerConfirm on urp.urpSn equals urpc.uRolePowerSn
                                                 join urpcr in uRolePowerConfirmRole on urpc.ucrSn equals urpcr.uRolePowerConfirmSn
                                                 where urp.uRoleID == roleID && urp.powerID == upower.powerID
                                                 select urpcr.uConfirmRoleID;
                    List<uRolesDpmt> uRolesDpmtCList = new List<uRolesDpmt>();
                    foreach (var crole in croleList)
                    {
                        uRolesDpmt urd = (from ur in uRoles
                                          join d in department on ur.departmentID equals d.departmentID
                                          where ur.uRoleID == crole
                                          select new uRolesDpmt
                                          {
                                              uRoles = ur,
                                              Department = d.departmentName
                                          }).FirstOrDefault();
                        uRolesDpmtCList.Add(urd);
                    }
                    uPowerWithBool uPowerWithBool = new uPowerWithBool {
                        uPowers = upower,
                        hasPower = haspower,
                        rolesConfirm = uRolesDpmtCList
                    };
                    upwbList.Add(uPowerWithBool);
                }
                uPowerWithBoolPage upwbp = new uPowerWithBoolPage
                {
                    uPages = upage,
                    uPowerWithBool = upwbList
                };
                upwbpList.Add(upwbp);
            }

            return PartialView(upwbpList);
        }

        [HttpGet]
        public PartialViewResult EditRoleConfirm(int upowerID)
        {
            uRolePowerConfirm urpcList = (from c in db.uRolePowerConfirm
                                            join x in db.uRolePowers on c.uRolePowerSn equals x.urpSn
                                            where x.powerID == upowerID
                                            select c).FirstOrDefault();

            return PartialView(urpcList);
        }

        [HttpPost]
        public ActionResult EditRoleConfirm(uRolePowerConfirm model, FormCollection form)
        {
            string result = "";
            if (model.uRolePowerSn != -1)
            {
                uRolePowerConfirm urpc = db.uRolePowerConfirm.Where(n => n.uRolePowerSn == model.uRolePowerSn).ToList().FirstOrDefault();
                urpc.uEachRoleMinNum = model.uEachRoleMinNum;
                urpc.uTotlaRoleMinNum = model.uTotlaRoleMinNum;                
            }
            else
            {
                int roleID = Convert.ToInt32(form["roleID"]);
                int powerID = Convert.ToInt32(form["powerID"]);
                int urpsn = db.uRolePowers.Where(n => n.uRoleID == roleID && n.powerID == powerID).Select(n => n.urpSn).ToList().FirstOrDefault();
                uRolePowerConfirm urpc = new uRolePowerConfirm {
                    uRolePowerSn=urpsn,
                    uEachRoleMinNum=model.uEachRoleMinNum,
                    uTotlaRoleMinNum=model.uTotlaRoleMinNum
                };
                db.uRolePowerConfirm.Add(urpc);
            }
            db.SaveChanges();
            result = "角色覆核人數設定更新成功";
            return Content(result);
        }
        
        public JsonResult EditRoleConfirmRole(int urpSn)
        {
            IEnumerable<uRolesWithDpmtSurName> result = urpSn == -1 ? null : (from cr in db.uRolePowerConfirmRole
                                                               join rc in db.uRolePowerConfirm on cr.uRolePowerConfirmSn equals rc.ucrSn
                                                               join r in db.uRoles on cr.uConfirmRoleID equals r.uRoleID
                                                               join d in db.Department on r.departmentID equals d.departmentID
                                                               where rc.uRolePowerSn == urpSn
                                                               select new uRolesWithDpmtSurName
                                                               {
                                                                   uRoles =r,
                                                                   Department =d.departmentName
                                                               });
            
            List<uRolesWithDpmtSurName> resultli = new List<uRolesWithDpmtSurName>();
            if (result!=null)
            {
                IEnumerable<uRoles> uRoleO = db.uRoles.ToList();
                foreach (var rff in result)
                {
                    if (rff.uRoles.supervisorID.HasValue)
                    {
                        rff.uRoleSurName = uRoleO.Where(n => n.uRoleID == rff.uRoles.supervisorID.Value).Select(n => n.uRoleName).FirstOrDefault();
                    }
                    else
                    {
                        rff.uRoleSurName = "無";
                    }
                    resultli.Add(rff);
                }
            }
            return Json(resultli, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult EditRoleConfirmRole(FormCollection form)
        {
            string result = "";
            int roleID = Convert.ToInt32(form["roleID"]);
            int powerID = Convert.ToInt32(form["powerID"]);
            List<int> editRoleConfirmRoleList = new List<int>();
            foreach (var key in form.AllKeys)
            {
                if (key.Contains("crID"))
                {
                    editRoleConfirmRoleList.Add(int.Parse(form.Get(key)));
                }
            }
            int urpsn = db.uRolePowers.Where(n => n.uRoleID == roleID && n.powerID == powerID).Select(n => n.urpSn).ToList().FirstOrDefault();
            int ucrsn = db.uRolePowerConfirm.Where(n => n.uRolePowerSn==urpsn).Select(n => n.ucrSn).ToList().FirstOrDefault();
            IEnumerable<uRolePowerConfirmRole> urpcrs = from rc in db.uRolePowerConfirm
                                                          join cr in db.uRolePowerConfirmRole on rc.ucrSn equals cr.uRolePowerConfirmSn
                                                          where rc.uRolePowerSn == urpsn
                                                          select cr;

            foreach (uRolePowerConfirmRole urpcr in urpcrs)
            {
                if (editRoleConfirmRoleList.Contains(urpcr.uConfirmRoleID))
                {
                    editRoleConfirmRoleList.Remove(urpcr.uConfirmRoleID);
                }
                else
                {
                    db.uRolePowerConfirmRole.Remove(urpcr);
                }
            }
            foreach (int croleid in editRoleConfirmRoleList)
            {
                uRolePowerConfirmRole urpcr = new uRolePowerConfirmRole
                {
                    uRolePowerConfirmSn= ucrsn,
                    uConfirmRoleID=croleid
                };
                db.uRolePowerConfirmRole.Add(urpcr);
            }
            db.SaveChanges();
            result = "角色覆核角色更新成功";
            return Content(result);
        }

        public JsonResult ECGetRolesList(int roleID=-1,int options=-1)
        {
            IEnumerable<uRoles> result = db.uRoles.ToList();
            IEnumerable<uRoles> uRoleO = db.uRoles.ToList();
            if (roleID!=-1&& options!=-1)
            {
                uRoles rfilter = db.uRoles.Where(n => n.uRoleID == roleID).FirstOrDefault();
                switch (options)
                {
                    case 1:                        
                        result = result.Where(n => n.uRoleID == rfilter.supervisorID);
                        break;
                    case 2:
                        List<uRoles> rList = new List<uRoles>();
                        if (rfilter != null)
                        {
                            if (rfilter.supervisorID.HasValue)
                            {

msit116apexLayout/Views/PowerConfirm/EditRoleConfirm.cshtml
@model msit116apexLayout.Models.uRolePowerConfirm


@using (Html.BeginForm("EditRoleConfirm", "PowerConfirm", new { area = "" }, FormMethod.Post, new { @class = "form-horizontal", role = "form", id = "editRoleConfirmForm" }))
{
    if (@Model != null)
    {
    <input type="hidden" id="uRolePowerSn" name="uRolePowerSn" value="@Model.uRolePowerSn"/>
    }
    else
    {
        <input type="hidden" id="uRolePowerSn" name="uRolePowerSn" value="-1" />
    }
        
    <div class="form-group">
        @Html.LabelFor(n => n.uEachRoleMinNum, new { @class = "col-md-3 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.uEachRoleMinNum, new { htmlAttributes = new { @class = "form-control",min="0" } })            
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(n => n.uTotlaRoleMinNum, new { @class = "col-md-3 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.uTotlaRoleMinNum, new { htmlAttributes = new { @class = "form-control", min = "0" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(n => n.rolePriority, new { @class = "col-md-3 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.rolePriority, new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(n => n.maxDay, new { @class = "col-md-3 control-label" })
        <div class="col-md-10">
            @Html.EditorFor(m => m.maxDay, new { htmlAttributes = new { @class = "form-control", min = "0" } })
        </div>
    </div>
    <div class="form-group">
        <label class = "col-md-3">覆核角色</label>
        <div class="form-inline">
            <div id="selectViewRoleConfirmRoleDiv">

            </div>
            <input id="btnAddUserToRoleCR" type="button" class="btn btn-primary" value="+" />
            <input id="ECroleListOption1" type="radio" name="ECroleListOptions" value="-1"/>
            <label for="ECroleListOption1">無</label>
            <input id="ECroleListOption2" type="radio" name="ECroleListOptions" value="1" checked/>
            <label for="ECroleListOption2">只顯示上一層主管</label>
            <input id="ECroleListOption3" type="radio" name="ECroleListOptions" value="2"/>
            <label for="ECroleListOption3">顯示所有上級主管</label>
        </div>
        
        <div>
            <ul id="selectedRCRolesUL">

            </ul>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <span>
                當使用者擁有多個角色時，依據下列條件順序選擇使用的角色覆核設定：
            </span>
            <span>1.以優先度最高的，如無設定優先度為最低。</span>
            <span>2.以'覆核角色'中階層最高的</span>
            <span>3.以'覆核角色'需要角色最多的</span>
            <span>4.以'所有角色最少確認人數'最多的</span>
            <span>5.以'每個角色最少確認人數'最多的</span>
            <span>6.以'角色創建時間'最早的</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="btnEditRoleConfirmSubmit" type="button" value="完成編輯" class="btn btn-primary" />
        </div>
    </div>
}



<script>
    $(function () {
        var urpSn = parseInt($("#uRolePowerSn").val());
        if (!urpSn)
            urpSn = -1;
        $.get("@Url.Action("EditRoleConfirmRole", "PowerConfirm", new { area=""})?urpSn=" + urpSn, null, function (data) {
            $.each(data, function (idv, objv) {
                var labelname = $('<label>' + objv.uRoles.uRoleName + '</label>');
                var labelname2 = $('<label>&lt部門: ' + objv.Department + '&gt</label>');
                var labelname3 = $('<label>&lt主管: ' + objv.uRoleSurName + '&gt</label>');
                var reruBtn = $('<input type="button" class="btn btn-primary" value="-" />');
                var addli = $("<li name=lirid" + objv.uRoles.uRoleID + "></li>")
                    .append(labelname)
                    .append(labelname2)
                    .append(labelname3)
                    .append(reruBtn)
                    .data("rn", objv.uRoles.uRoleName)
                    .data("d", objv.Department)
                    .data("rsn", objv.uRoleSurName);
                var eruList = $("#selectedRCRolesUL");
                $(eruList).append(addli);
            });
        });
        $.get("@Url.Action("ECGetRolesList", "PowerConfirm", new { area=""})?roleID=" + $('#selectViewRoleConfirmSelect').val() + "&options=" + $('input:radio[name="ECroleListOptions"]:checked').val(), null, function (data) {
                var sx1s = $('<select id="selectVRCRSelect"></select>').addClass('form-control').prepend("<option value=''>請選擇</option>");
                $.each(data, function (idv, objv) {
                    var sx1 = $("<option></option>")
                        .attr("value", objv.uRoles.uRoleID)
                        .data("rn", objv.uRoles.uRoleName)
                        .data("d", objv.Department)
                        .data("rsn", objv.uRoleSurName)
                        .text(objv.uRoles.uRoleName + "<部門:" + objv.Department + "><主管:" + objv.uRoleSurName + ">");
                    sx1s.append(sx1);
                });
                $('#selectViewRoleConfirmRoleDiv').html(sx1s);
        });
        $('input:radio[name="ECroleListOptions"]').change(function () {
            var ecrval = $(this).val();
            var roleID = $('#selectViewRoleConfirmSelect').val();
            switch (ecrval)
            {
                case "1":
                case "2":
                case "-1":
                    $.get("@Url.Action("ECGetRolesList", "PowerConfirm", new { area=""})?roleID=" + roleID + "&options=" + ecrval, null, function (data) {
                        var sx1s = $('<select id="selectVRCRSelect"></select>').addClass('form-control').prepend("<option value=''>請選擇</option>");
                        $.each(data, function (idv, objv) {
                            var sx1 = $("<option></option>")
                                .attr("value", objv.uRoles.uRoleID)
                                .data("rn", objv.uRoles.uRoleName)
                                .data("d", objv.Department)
                                .data("rsn", objv.uRoleSurName)
                                .text(objv.uRoles.uRoleName + "<部門:" + objv.Department + "><主管:" + objv.uRoleSurName+">");
                            sx1s.append(sx1);
                        });
                        $('#selectViewRoleConfirmRoleDiv').html(sx1s);
                    });
                default:
                    break;
            }
        });
        $("#btnAddUserToRoleCR").click(function () {
            var utxt = $("#selectVRCRSelect option:selected");
            var labelname = $('<label>' + utxt.data("rn") + '</label>');
            var labelname2 = $('<label>&lt部門: ' + utxt.data("d") + '&gt</label>');
            var labelname3 = $('<label>&lt主管: ' + utxt.data("rsn") + '&gt</label>');
            var reruBtn = $('<input type="button" class="btn btn-primary" value="-" />');
            var addli = $("<li name=lirid" + $(utxt).val() + "></li>")
                .append(labelname)
                .append(labelname2)
                .append(labelname3)
                .append(reruBtn)
                .data("rn", utxt.data("rn"))
                .data("d", utxt.data("d"))
                .data("rsn", utxt.data("rsn"));
            var eruList = $("#selectedRCRolesUL");
            //var limitLength = $("#editRoleUserLimit").val();
            var currentLength = $("#selectedRCRolesUL li").length;
            if ($(eruList).children("li[name='lirid" + $(utxt).val()+"']").length == 0) {
                //if (limitLength > currentLength)
                    $(eruList).append(addli);
            }
        });
        $("#selectedRCRolesUL").on('click', "input[value='-']", function () {
            $(this).parent().remove();
        });
        $('#btnEditRoleConfirmSubmit').click(function () {
            var eruList = $("#selectedRCRolesUL li");
            var returnArray = {};
            returnArray["roleID"] = $('#selectViewRoleConfirmSelect').val();
            returnArray["powerID"] = $('#selectRoleCEditPower').val();
            var count = 1;
            $.each(eruList, function () {
                var uname = "crID" + count;
                returnArray[uname] = $(this).attr("name").split("lirid")[1];
                count = count + 1;
            });

            var formArray = $('#editRoleConfirmForm').serializeArray();
            var returnArray1 = {};
            for (var i = 0; i < formArray.length; i++) {
                returnArray1[formArray[i]['name']] = formArray[i]['value'];
            };
            returnArray1["roleID"] = $('#selectViewRoleConfirmSelect').val();
            returnArray1["powerID"] = $('#selectRoleCEditPower').val();
            var pid = $('#selectRoleCEditPower').val();

            $.post('@Url.Action("EditRoleConfirm", "PowerConfirm", new { area = "" })', returnArray1, function (data) {
                //Finsehed Update
                $('#returnMessage1').text(data).css("display", "block");
                var msg1 = data;
                $.post('@Url.Action("EditRoleConfirmRole", "PowerConfirm", new { area = "" })', returnArray, function (data) {
                    $('#returnMessage2').text(data).css("display", "block");
                    //Finsehed Update
                    var msg2 = data;
                    if (msg1 == "角色覆核人數設定更新成功")
                        if (msg2 == "角色覆核角色更新成功")
                        {
                            var eul = $('#urpEditID' + $('#selectRoleCEditPower').val()).parent().next("ul");
                            eul.html("");
                            $.each(eruList, function () {
                                console.log($(this).data("rn"));
                                var editedeurli = $('<li></li>').text($(this).data("rn") + "<" + $(this).data("d") + ">");
                                eul.append(editedeurli);
                            });
                        }

                    //Reload
                    @*$.get("@Url.Action("EditRoleConfirm", "PowerConfirm", new { area=""})?upowerID=" + pid, function (data) {

                        $('#loadEditRoleConfirmRole').html(data);
                    });*@
                });
            });


        });
    });
</script>

msit116apexLayout/Views/PowerConfirm/Index.cshtml
@{
    ViewBag.Title = "角色覆核管理";
}
<div class="row">
    <div class="col-lg-1"></div>
    <div class="col-lg-10">
        <div class="card">
            <h4 class="card-header bg-info text-white">角色覆核管理</h4>
            <div class="card-body">

                <div>
                    <div id="selectViewRoleConfirmDiv" class="col-md-4">

                    </div>
                    <div id="loadViewRoleConfirmContent" style="padding:3px">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        $(function () {
            $.get("@Url.Action("GetRolesList", "Power",new { area=""})", null, function (data) {
                var sx1s = $('<select id="selectViewRoleConfirmSelect"></select>').addClass('form-control').prepend("<option value=''>請選擇</option>");
                $.each(data, function (idv, objv) {
                    var sx1 = $("<option></option>")
                        .attr("value", objv.uRoles.uRoleID)
                        .text(objv.uRoles.uRoleName);
                    sx1s.append(sx1);
                });
                $('#selectViewRoleConfirmDiv').html(sx1s);
            });
            $('#selectViewRoleConfirmDiv').on('change', '#selectViewRoleConfirmSelect', function () {
                var rid = parseInt($(this).val());
                if (rid) {
                    $.get('@Url.Action("ViewRoleConfirm")?roleID=' + rid, function (data) {
                        $('#loadViewRoleConfirmContent').html(data);
                    });
                }
                else
                {
                    $('#loadViewRoleConfirmContent').html("");
                }
            });
        });
    </script>
    }

msit116apexLayout/Views/PowerConfirm/ViewRoleConfirm.cshtml
@model IEnumerable<msit116apexLayout.Models.uPowerWithBoolPage>

<style>
    .seleceEditPowerBtn {
        /*box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);*/
        border:3px dashed black;
        font-weight:bold;
    }
</style>
<div style="padding-left:1em">
    <div class="row" style="margin:0px;padding:0px">
        <div class="col-lg-4" style="border:1px silver solid;border-radius:3px">
            <input type="hidden" id="selectRoleCEditPower" />
            <ul>
                @foreach (var upwbp in Model)
            {
                    <li>
                        @upwbp.uPages.pageName
                        <ul>
                            @foreach (var upower in upwbp.uPowerWithBool)
                        {
                                <li>
                                    @if (@upower.hasPower)
                                {
                                        <div>
                                            <span>
                                                @upower.uPowers.powerName
                                            </span>
                                            <button id="@string.Format("urpEditID{0}",@upower.uPowers.powerID)" class="btn btn-warning">
                                                選擇編輯
                                            </button>
                                        </div>
                                        <ul>
                                            覆核角色
                                            @foreach (var curole in upower.rolesConfirm)
                                        {
                                                <li>
                                                    @string.Format("{0}<{1}>", @curole.uRoles.uRoleName, curole.Department)
                                                </li>
                                        }
                                        </ul>
                                }
                                else
                                {
                                        <span style="color:silver">
                                            @upower.uPowers.powerName
                                        </span>
                                }
                                </li>
                        }
                        </ul>
                    </li>
            }
            </ul>
        </div>
        <div class="col-lg-8" style="border:1px silver solid;border-radius:3px">
            <span id="returnMessage1" class="text-success" style="display:none"></span>
            <span id="returnMessage2" class="text-success" style="display:none"></span>
            <div id="loadEditRoleConfirmRole">

            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        $('button[id^="urpEditID"]').click(function () {
            $('#returnMessage1').text("").css("display","none");
            $('#returnMessage2').text("").css("display", "none");
            var oldpid = $('#selectRoleCEditPower').val();
            $('button[id="urpEditID' + oldpid + '"]').removeClass("seleceEditPowerBtn").text("選擇編輯");
            var newpid = $(this).attr("id").split("urpEditID")[1];
            if (oldpid != newpid) {
                $('#selectRoleCEditPower').val(newpid);
                $(this).addClass("seleceEditPowerBtn").text("編輯中");
                $.get("@Url.Action("EditRoleConfirm", "PowerConfirm", new { area=""})?upowerID=" + newpid, function (data) {
                    $('#loadEditRoleConfirmRole').html(data);
                });
            }
            else {
                $('#selectRoleCEditPower').val("").text("選擇編輯");
                $('#loadEditRoleConfirmRole').html("");
            }

        });
    });
</script>